Repository awesome-streamers/awesome-streamerrc, pull requests merged in 2020-11, with the labels that each got.

#12 Added checks for plugin existence
  TheAltF4Stream/Dockerfile
  TheAltF4Stream/init.vim
Labels: enhancement, good first issue

#11 updates: thealtf4stream begins work on Docker neovim env
  TheAltF4Stream/.dockerignore
  TheAltF4Stream/.gitignore
  TheAltF4Stream/Dockerfile
  TheAltF4Stream/README.md
  TheAltF4Stream/autoload.Dockerfile
  TheAltF4Stream/init.vim
  TheAltF4Stream/scripts/autoload_entrypoint.sh
  TheAltF4Stream/scripts/default_entrypoint.sh
Labels: enhancement

#14 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#15 MelkeyVimRC
  MelkeyDev/InstallDotNet
  MelkeyDev/coc-settings.json
  MelkeyDev/init.vim
  MelkeyDev/lua/init.lua
Labels: enhancement
